-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker - https://www.codeandweb.com/texturepacker
-- $TexturePacker:SmartUpdate:14084df5ce6ca7508347d9ec7d930838:4d0cd494931b5c5a590c9f268c100088:867d1c8a498704d7aca93f56937c973d$
-- 

return {
	texture = 'moai.png',
	frames = {
			{
				name = "icon_16",
				spriteColorRect = { x = 0, y = 0, width = 16, height = 16 },
				uvRect = { u0 = 0.876682, v0 = 0.857741, u1 = 0.912556, v1 = 0.924686 },
				spriteSourceSize = { width = 16, height = 16 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "icon_32",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 32 },
				uvRect = { u0 = 0.800448, v0 = 0.857741, u1 = 0.872197, v1 = 0.991632 },
				spriteSourceSize = { width = 32, height = 32 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "icon_48",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 48 },
				uvRect = { u0 = 0.85426, v0 = 0.280335, u1 = 0.961883, v1 = 0.481172 },
				spriteSourceSize = { width = 48, height = 48 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "icon_64",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.85426, v0 = 0.0041841, u1 = 0.997758, v1 = 0.271967 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "icon_72",
				spriteColorRect = { x = 0, y = 0, width = 72, height = 72 },
				uvRect = { u0 = 0.800448, v0 = 0.548117, u1 = 0.961883, v1 = 0.849372 },
				spriteSourceSize = { width = 72, height = 72 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "icon_96",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 96 },
				uvRect = { u0 = 0.580718, v0 = 0.548117, u1 = 0.795964, v1 = 0.949791 },
				spriteSourceSize = { width = 96, height = 96 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "icon_128",
				spriteColorRect = { x = 0, y = 7, width = 128, height = 120 },
				uvRect = { u0 = 0.580718, v0 = 0.0041841, u1 = 0.849776, v1 = 0.539749 },
				spriteSourceSize = { width = 128, height = 128 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "icon_256",
				spriteColorRect = { x = 0, y = 15, width = 256, height = 237 },
				uvRect = { u0 = 0.00224215, v0 = 0.0041841, u1 = 0.576233, v1 = 0.995816 },
				spriteSourceSize = { width = 256, height = 256 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

