/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:4deb6f5a798c67933ac414fdceaeedf1:4d0cd494931b5c5a590c9f268c100088:ece9fe176060f5f386bf318a95b81875$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string icon_16 = "icon_16";
		public const string icon_32 = "icon_32";
		public const string icon_48 = "icon_48";
		public const string icon_64 = "icon_64";
		public const string icon_72 = "icon_72";
		public const string icon_96 = "icon_96";
		public const string icon_128 = "icon_128";
		public const string icon_256 = "icon_256";
	}
}